{
  "openapi": "3.0.3",
  "info": {
    "title": "Presence API",
    "description": "This is a Presence API based on the OpenAPI 3.0 specification. ",
    "version": "1.0.0",
    "contact": {
      "name": "navetacandra",
      "email": "naveta.cand@gmail.com",
      "url": "https://navetacandra.github.io/"
    }
  },
  "servers": [
    {
      "url": "http://localhost:3000/api/v1",
      "description": "Local development server"
    }
  ],
  "tags": [
    {
      "name": "mode",
      "description": "Operations about mode"
    },
    {
      "name": "schedule",
      "description": "Operations about schedule"
    },
    {
      "name": "student",
      "description": "Operations about student"
    },
    {
      "name": "whatsapp",
      "description": "Operations about whatsapp"
    }
  ],
  "paths": {
    "/mode": {
      "get": {
        "summary": "Get mode",
        "tags": [
          "mode"
        ],
        "responses": {
          "200": {
            "description": "Successful get mode",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "#/components/schemas/Mode"
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "add": {
                    "value": {
                      "success": true,
                      "code": 200,
                      "data": {
                        "mode": "add"
                      }
                    }
                  },
                  "presence": {
                    "value": {
                      "success": true,
                      "code": 200,
                      "data": {
                        "mode": "presence"
                      }
                    }
                  }
                }
              },
              "text/event-stream": {
                "schema": {
                  "type": "string",
                  "properties": {
                    "data": {
                      "$ref": "#/components/schemas/Mode"
                    }
                  }
                },
                "examples": {
                  "add": {
                    "value": "data: {\"mode\": \"add\"}"
                  },
                  "presence": {
                    "value": "data: {\"mode\": \"presence\"}"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update mode",
        "tags": [
          "mode"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Mode"
              },
              "examples": {
                "add": {
                  "value": {
                    "mode": "add"
                  }
                },
                "presence": {
                  "value": {
                    "mode": "presence"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful update mode",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "#/components/schemas/Mode"
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "add": {
                    "value": {
                      "success": true,
                      "code": 200,
                      "data": {
                        "mode": "add"
                      }
                    }
                  },
                  "presence": {
                    "value": {
                      "success": true,
                      "code": 200,
                      "data": {
                        "mode": "presence"
                      }
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid mode",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "success": false,
                  "code": 400,
                  "error": {
                    "message": "Invalid mode",
                    "code": "INVALID_DATA"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/schedule-detail": {
      "get": {
        "summary": "Get schedule detail",
        "tags": [
          "schedule"
        ],
        "responses": {
          "200": {
            "description": "Successful get schedule detail",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/ScheduleDetail"
                          }
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "code": 200,
                  "data": {
                    "masukStart": "05:00",
                    "masukEnd": "06:30",
                    "pulangStart": "15:00",
                    "pulangEnd": "18:00"
                  }
                }
              },
              "text/event-stream": {
                "schema": {
                  "type": "string",
                  "properties": {
                    "data": {
                      "$ref": "#/components/schemas/ScheduleDetail"
                    }
                  }
                },
                "example": "data: {\"masukStart\": \"05:00\", \"masukEnd\": \"06:30\", \"pulangStart\": \"15:00\", \"pulangEnd\": \"18:00\"}"
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update schedule detail",
        "tags": [
          "schedule"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/ScheduleDetail"
              },
              "example": {
                "masukStart": "06:00",
                "masukEnd": "08:00",
                "pulangStart": "16:00",
                "pulangEnd": "20:00"
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful update schedule detail",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "#/components/schemas/ScheduleDetail"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "code": 200,
                  "data": {
                    "masukStart": "06:00",
                    "masukEnd": "08:00",
                    "pulangStart": "16:00",
                    "pulangEnd": "20:00"
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "success": false,
                  "code": 400,
                  "error": {
                    "message": "\"masukStart\" is invalid",
                    "code": "INVALID_DATA"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/schedule": {
      "get": {
        "summary": "Get schedule",
        "tags": [
          "schedule"
        ],
        "responses": {
          "200": {
            "description": "Successful get schedule",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/ScheduleWithId"
                          }
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "code": 200,
                  "data": [
                    {
                      "_id": "1",
                      "month": "januari",
                      "date": "1",
                      "isActive": false
                    },
                    {
                      "_id": "2",
                      "month": "januari",
                      "date": "2",
                      "isActive": true
                    }
                  ]
                }
              },
              "text/event-stream": {
                "schema": {
                  "type": "string",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/ScheduleWithId"
                      }
                    }
                  }
                },
                "example": "data: [{\"_id\":\"1\",\"month\":\"januari\",\"date\":\"1\",\"isActive\":false}, {\"_id\":\"2\",\"month\":\"januari\",\"date\":\"2\",\"isActive\":true}]"
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update schedule",
        "tags": [
          "schedule"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Schedule"
              },
              "example": {
                "month": "januari",
                "date": "1",
                "isActive": true
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful update schedule",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/ScheduleWithId"
                          }
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "code": 200,
                  "data": [
                    {
                      "_id": "1",
                      "month": "januari",
                      "date": "1",
                      "isActive": true
                    },
                    {
                      "_id": "2",
                      "month": "januari",
                      "date": "2",
                      "isActive": true
                    }
                  ]
                }
              }
            }
          },
          "400": {
            "description": "Invalid data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "success": false,
                  "code": 400,
                  "error": {
                    "message": "\"month\" is required",
                    "code": "INVALID_DATA"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Date not found",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "success": false,
                  "code": 404,
                  "error": {
                    "message": "\"date\" is not found",
                    "code": "DATE_NOT_FOUND"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/students": {
      "get": {
        "summary": "Get students",
        "tags": [
          "student"
        ],
        "responses": {
          "200": {
            "description": "Successful get students",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "array",
                          "items": {
                            "allOf": [
                              {
                                "type": "object",
                                "properties": {
                                  "_id": {
                                    "type": "string"
                                  }
                                },
                                "required": [
                                  "_id"
                                ]
                              },
                              {
                                "$ref": "#/components/schemas/Student"
                              }
                            ]
                          }
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "code": 200,
                  "data": [
                    {
                      "_id": "1",
                      "nis": "123456789",
                      "nama": "Abraham Billy Marawali",
                      "email": "abraham@gmail.com",
                      "kelas": "11 RPL1",
                      "alamat": "Tangerang, Banten",
                      "telSiswa": "08123456789",
                      "telWaliMurid": "08123456789",
                      "telWaliKelas": "08123456789"
                    },
                    {
                      "_id": "2",
                      "nis": "012345678",
                      "nama": "Ailda Prima Yukayla",
                      "email": "ailda@gmail.com",
                      "kelas": "11 RPL1",
                      "alamat": "Tangerang, Banten",
                      "telSiswa": "08123456789",
                      "telWaliMurid": "08123456789",
                      "telWaliKelas": "08123456789",
                      "card": "-A0-4G-33-FE"
                    }
                  ]
                }
              },
              "text/event-stream": {
                "schema": {
                  "type": "string",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/Student"
                      }
                    }
                  },
                  "example": "data: [{\"_id\":\"1\",\"nis\": \"123456789\",\"nama\":\"AbrahamBillyMarawali\",\"email\":\"abraham@gmail.com\",\"kelas\":\"11RPL1\",\"alamat\":\"Tangerang,Banten\",\"telSiswa\":\"08123456789\",\"telWaliMurid\":\"08123456789\",\"telWaliKelas\":\"08123456789\",}, {\"_id\":\"2\",\"nis\": \"012345678\",\"nama\":\"AildaPrimaYukayla\",\"email\":\"ailda@gmail.com\",\"kelas\":\"11RPL1\",\"alamat\":\"Tangerang,Banten\",\"telSiswa\":\"08123456789\",\"telWaliMurid\":\"08123456789\",\"telWaliKelas\":\"08123456789\",\"card\":\"-A0-4G-33-FE\"}]"
                }
              }
            }
          }
        }
      },
      "post": {
        "summary": "Create new student",
        "tags": [
          "student"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Student"
              },
              "examples": {
                "withoutCard": {
                  "value": {
                    "nis": "001234567",
                    "nama": "Adinda Salsabila",
                    "email": "adinda@gmail.com",
                    "kelas": "11 RPL1",
                    "alamat": "Tangerang, Banten",
                    "telSiswa": "08123456789",
                    "telWaliMurid": "08123456789",
                    "telWaliKelas": "08123456789"
                  }
                },
                "withCard": {
                  "value": {
                    "nis": "001234567",
                    "nama": "Adinda Salsabila",
                    "email": "adinda@gmail.com",
                    "kelas": "11 RPL1",
                    "alamat": "Tangerang, Banten",
                    "telSiswa": "08123456789",
                    "telWaliMurid": "08123456789",
                    "telWaliKelas": "08123456789",
                    "card": "-55-A3-BF-G1"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful create new student",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "example": "3"
                    },
                    "nama": {
                      "type": "string",
                      "example": "Adinda Salsabila"
                    },
                    "nis": {
                      "type": "string",
                      "example": "001234567"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "success": false,
                  "code": 400,
                  "error": {
                    "message": "nis already registered",
                    "code": "NIS_ALREADY_REGISTERED"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/student/{studentId}": {
      "parameters": [
        {
          "in": "path",
          "name": "studentId",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "summary": "Get student by id",
        "tags": [
          "student"
        ],
        "responses": {
          "200": {
            "description": "Successful get student by id",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "#/components/schemas/Student"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "code": 200,
                  "data": {
                    "_id": "1",
                    "nis": "123456789",
                    "nama": "Abraham Billy Marawali",
                    "email": "abraham@gmail.com",
                    "kelas": "11 RPL1",
                    "alamat": "Tangerang, Banten",
                    "telSiswa": "08123456789",
                    "telWaliMurid": "08123456789",
                    "telWaliKelas": "08123456789"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Student not registered",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "success": false,
                  "code": 404,
                  "error": {
                    "message": "Student is not registered",
                    "code": "STUDENT_NOT_REGISTERED"
                  }
                }
              }
            }
          }
        }
      },
      "put": {
        "summary": "Update student by id",
        "tags": [
          "student"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/Student"
              },
              "examples": {
                "withoutCard": {
                  "value": {
                    "nis": "001234567",
                    "nama": "Adinda Salsabila",
                    "email": "emailnya.adinda@gmail.com",
                    "kelas": "11 RPL1",
                    "alamat": "Tangerang, Banten",
                    "telSiswa": "08123456789",
                    "telWaliMurid": "08123456789",
                    "telWaliKelas": "08123456789"
                  }
                },
                "withCard": {
                  "value": {
                    "nis": "001234567",
                    "nama": "Adinda Salsabila",
                    "email": "emailnya.adinda@gmail.com",
                    "kelas": "11 RPL1",
                    "alamat": "Tangerang, Banten",
                    "telSiswa": "08123456789",
                    "telWaliMurid": "08123456789",
                    "telWaliKelas": "08123456789",
                    "card": "-55-A3-BF-G1"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful create new student",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "string",
                      "example": "3"
                    },
                    "nama": {
                      "type": "string",
                      "example": "Adinda Salsabila"
                    },
                    "nis": {
                      "type": "string",
                      "example": "001234567"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid data",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "success": false,
                  "code": 400,
                  "error": {
                    "message": "\"email\" is required",
                    "code": "INVALID_DATA"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Student not registered",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "success": false,
                  "code": 404,
                  "error": {
                    "message": "Student is not registered",
                    "code": "STUDENT_NOT_REGISTERED"
                  }
                }
              }
            }
          }
        }
      },
      "delete": {
        "summary": "Delete student by id",
        "tags": [
          "student"
        ],
        "responses": {
          "200": {
            "description": "Successful delete student",
            "content": {
              "appliaction/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "object",
                          "properties": {
                            "id": {
                              "type": "string",
                              "example": "1"
                            },
                            "nama": {
                              "type": "string",
                              "example": "Abraham Billy Marawali"
                            },
                            "nis": {
                              "type": "string",
                              "example": "123465879"
                            }
                          }
                        }
                      }
                    }
                  ]
                }
              }
            }
          },
          "404": {
            "description": "Student not registered",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "success": false,
                  "code": 404,
                  "error": {
                    "message": "Student is not registered",
                    "code": "STUDENT_NOT_REGISTERED"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/whatsapp": {
      "get": {
        "summary": "Get whatsapp state",
        "tags": [
          "whatsapp"
        ],
        "responses": {
          "200": {
            "description": "Successful get whatsapp state",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "oneOf": [
                            {
                              "$ref": "#/components/schemas/WhatsAppNotLogedIn"
                            },
                            {
                              "$ref": "#/components/schemas/WhatsAppLogedIn"
                            }
                          ]
                        }
                      }
                    }
                  ]
                },
                "examples": {
                  "notLogedIn": {
                    "value": {
                      "success": true,
                      "code": 200,
                      "data": {
                        "isReady": false,
                        "qrcode": "base64:image/png,..."
                      }
                    }
                  },
                  "logedIn": {
                    "value": {
                      "success": true,
                      "code": 200,
                      "data": {
                        "isReady": true,
                        "user": {
                          "id": "6281234567890:2@s.whatsapp.net",
                          "name": "[bot]"
                        }
                      }
                    }
                  }
                }
              },
              "text/event-stream": {
                "schema": {
                  "type": "string",
                  "properties": {
                    "data": {
                      "oneOf": [
                        {
                          "$ref": "#/components/schemas/WhatsAppNotLogedIn"
                        },
                        {
                          "$ref": "#/components/schemas/WhatsAppLogedIn"
                        }
                      ]
                    }
                  }
                },
                "examples": {
                  "notLogedIn": {
                    "value": "data: {\"isReady\":false,\"qrcode\":\"base64:image/png,...\"}"
                  },
                  "logedIn": {
                    "value": "data: {\"isReady\":true,\"user\":{\"id\":\"6281234567890:2@s.whatsapp.net\",\"name\":\"[bot]\"}}"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/on-whatsapp/{number}": {
      "parameters": [
        {
          "in": "path",
          "name": "number",
          "required": true,
          "schema": {
            "type": "string",
            "pattern": "\\d{10,13}"
          }
        }
      ],
      "get": {
        "summary": "Get is number registered",
        "tags": [
          "whatsapp"
        ],
        "responses": {
          "200": {
            "description": "Number is registered",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "$ref": "#/components/schemas/WhatsAppIsRegistered"
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "code": 200,
                  "data": {
                    "number": "08123456789",
                    "prettifiedNumber": "628123456789",
                    "jid": "628123456789@s.whatsapp.net",
                    "isRegistered": true
                  }
                }
              }
            }
          },
          "400": {
            "description": "Invalid number",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "success": false,
                  "code": 400,
                  "error": {
                    "message": "\"number\" is invalid",
                    "code": "INVALID_DATA"
                  }
                }
              }
            }
          },
          "404": {
            "description": "Number not registered",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponse"
                },
                "example": {
                  "success": false,
                  "code": 404,
                  "error": {
                    "message": "\"number\" is not registered",
                    "code": "NUMBER_NOT_REGISTERED"
                  }
                }
              }
            }
          }
        }
      }
    },
    "/presence": {
      "get": {
        "summary": "Get list of students attended today",
        "tags": [
          "attendance"
        ],
        "responses": {
          "200": {
            "description": "Successful get list of students",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "type": "array",
                          "items": {
                            "$ref": "#/components/schemas/AttendedStudent"
                          }
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "code": 200,
                  "data": [
                    {
                      "studentId": "2",
                      "masuk": "06:00",
                      "status": "tepat",
                      "pulang": "16:30"
                    },
                    {
                      "studentId": "3",
                      "masuk": "06:00",
                      "status": "tepat",
                      "pulang": "17:30"
                    }
                  ]
                }
              },
              "text/event-stream": {
                "schema": {
                  "type": "string",
                  "properties": {
                    "data": {
                      "type": "array",
                      "items": {
                        "$ref": "#/components/schemas/AttendedStudent"
                      }
                    }
                  }
                },
                "example": "data: [{\"studentId\":\"2\",\"masuk\":\"06:00\",\"status\":\"tepat\",\"pulang\":\"16:30\"}, {\"studentId\":\"3\",\"masuk\":\"06:00\",\"status\":\"tepat\",\"pulang\":\"17:30\"}]"
              }
            }
          }
        }
      },
      "post": {
        "summary": "Presence a tag",
        "tags": [
          "attendance"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "tag": {
                    "type": "string",
                    "pattern": "(-\\w{2}){4}",
                    "example": "-A0-4G-33-FE"
                  },
                  "time": {
                    "type": "string",
                    "minLength": 5,
                    "maxLength": 5,
                    "pattern": "([01][0-9]|2[0-3]):([0-5][0-9])",
                    "example": "06:00"
                  },
                  "month": {
                    "type": "string",
                    "example": "januari"
                  },
                  "date": {
                    "type": "string",
                    "example": "1"
                  }
                },
                "required": [
                  "tag",
                  "time",
                  "month",
                  "date"
                ]
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Successful do attendance",
            "content": {
              "application/json": {
                "schema": {
                  "allOf": [
                    {
                      "$ref": "#/components/schemas/Response"
                    },
                    {
                      "type": "object",
                      "properties": {
                        "data": {
                          "oneOf": [
                            {
                              "$ref": "#/components/schemas/Card"
                            },
                            {
                              "$ref": "#/components/schemas/AttendedStudent"
                            }
                          ]
                        }
                      }
                    }
                  ]
                },
                "example": {
                  "success": true,
                  "code": 200,
                  "data": {
                    "studentId": "2",
                    "status": "tepat",
                    "masuk": "06:00"
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
      "Student": {
        "type": "object",
        "properties": {
          "nis": {
            "type": "string"
          },
          "nama": {
            "type": "string"
          },
          "email": {
            "type": "string"
          },
          "kelas": {
            "type": "string"
          },
          "alamat": {
            "type": "string"
          },
          "telSiswa": {
            "type": "string"
          },
          "telWaliMurid": {
            "type": "string"
          },
          "telWaliKelas": {
            "type": "string"
          },
          "card": {
            "type": "string",
            "pattern": "/(-\\w{2}){4}/",
            "nullable": true
          }
        },
        "required": [
          "nama",
          "email",
          "kelas",
          "alamat",
          "telSiswa",
          "telWaliMurid",
          "telWaliKelas"
        ]
      },
      "Mode": {
        "type": "object",
        "properties": {
          "mode": {
            "type": "string",
            "pattern": "add|presence"
          }
        }
      },
      "ScheduleDetail": {
        "type": "object",
        "properties": {
          "masukStart": {
            "type": "string",
            "minLength": 5,
            "maxLength": 5,
            "pattern": "([01][0-9]|2[0-3]):([0-5][0-9])"
          },
          "masukEnd": {
            "type": "string",
            "minLength": 5,
            "maxLength": 5,
            "pattern": "([01][0-9]|2[0-3]):([0-5][0-9])"
          },
          "pulangStart": {
            "type": "string",
            "minLength": 5,
            "maxLength": 5,
            "pattern": "([01][0-9]|2[0-3]):([0-5][0-9])"
          },
          "pulangEnd": {
            "type": "string",
            "minLength": 5,
            "maxLength": 5,
            "pattern": "([01][0-9]|2[0-3]):([0-5][0-9])"
          }
        },
        "required": [
          "masukStart",
          "masukEnd",
          "pulangStart",
          "pulangEnd"
        ]
      },
      "Schedule": {
        "type": "object",
        "properties": {
          "month": {
            "type": "string",
            "maxLength": 2
          },
          "date": {
            "type": "string",
            "maxLength": 2
          },
          "isActive": {
            "type": "boolean"
          }
        },
        "required": [
          "month",
          "date",
          "isActive"
        ]
      },
      "ScheduleWithId": {
        "allOf": [
          {
            "type": "object",
            "properties": {
              "_id": {
                "type": "string"
              }
            },
            "required": [
              "_id"
            ]
          },
          {
            "$ref": "#/components/schemas/Schedule"
          }
        ]
      },
      "AttendedStudent": {
        "type": "object",
        "properties": {
          "studentId": {
            "type": "string"
          },
          "masuk": {
            "type": "string",
            "minLength": 5,
            "maxLength": 5,
            "pattern": "([01][0-9]|2[0-3]):([0-5][0-9])"
          },
          "pulang": {
            "type": "string",
            "minLength": 5,
            "maxLength": 5,
            "pattern": "([01][0-9]|2[0-3]):([0-5][0-9])"
          },
          "status": {
            "type": "string",
            "minLength": 5,
            "maxLength": 5,
            "pattern": "tepat|telat"
          }
        },
        "required": [
          "studentId"
        ]
      },
      "Card": {
        "type": "object",
        "properties": {
          "_id": {
            "type": "string"
          },
          "tag": {
            "type": "string",
            "pattern": "/(-\\w{2}){4}/"
          }
        },
        "required": [
          "tag"
        ]
      },
      "WhatsAppNotLogedIn": {
        "type": "object",
        "properties": {
          "isReady": {
            "type": "boolean",
            "default": false
          },
          "qrcode": {
            "type": "string",
            "example": "base64:image/png,..."
          }
        }
      },
      "WhatsAppLogedIn": {
        "type": "object",
        "properties": {
          "isReady": {
            "type": "boolean",
            "default": true
          },
          "user": {
            "type": "object",
            "properties": {
              "id": {
                "type": "string",
                "example": "6281234567890:2@s.whatsapp.net"
              },
              "name": {
                "type": "string",
                "example": "[bot]"
              }
            }
          }
        }
      },
      "WhatsAppIsRegistered": {
        "type": "object",
        "properties": {
          "number": {
            "type": "string"
          },
          "prettifiedNumber": {
            "type": "string"
          },
          "jid": {
            "type": "string"
          },
          "isRegistered": {
            "type": "boolean"
          }
        },
        "required": [
          "number",
          "prettifiedNumber",
          "jid",
          "isRegistered"
        ]
      },
      "ErrorResponse": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "code": {
            "type": "number"
          },
          "error": {
            "type": "object",
            "properties": {
              "message": {
                "type": "string"
              },
              "code": {
                "type": "string"
              }
            },
            "required": [
              "message",
              "code"
            ]
          }
        },
        "required": [
          "success",
          "code",
          "error"
        ]
      },
      "Response": {
        "type": "object",
        "properties": {
          "success": {
            "type": "boolean"
          },
          "code": {
            "type": "number"
          },
          "data": {
            "type": "object"
          }
        }
      }
    }
  }
}